version: '3'

services:
  listen-and-notify:
    # image: trugamr/listen-and-notify
    build: .
    container_name: listen-and-notify
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - API_KEY=${API_KEY}